### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by 2422453389** [zilong-thu/toast2.js#2]
在这个基础之上，再加一个loading的页面，就完美了，不忙的时候加一下把

**Comment by zilong-thu** [comment]
好的，感谢建议~~我这周加一下。

**Comment by zilong-thu** [comment]
@2422453389 ，加了一个比较粗糙的……两个 API
toast.showLoading()
toast.hideLoading()

还没有加 mask，下一步有空再加上~~

**Comment by zilong-thu** [comment]
@2422453389 ，嗨亲， mask 我也加上了。感谢建议哈~~ 我先关闭了~~
toast2@2.1.1 版本起开始支持~~
